#!/usr/bin/env bash

function dotfile {
    # shellcheck disable=SC2068
    /usr/bin/git --git-dir="$HOME/.local/dotfiles" --work-tree="$HOME" $@
}

result=$(dotfile pull)

grep "Already up to date." <(echo "$result") && ALREADY_UPDATED=1
grep "file changed" <(echo "$result") && SUCCESFUL_UPDATE=1
[[ $ALREADY_UPDATED -ne 1 && $SUCCESFUL_UPDATE -ne 1 ]] && NEEDS_MANUAL_INTERVENTION=1

[[ $ALREADY_UPDATED -eq 1 ]] && echo "Dotfiles are already updated!"

[[ $SUCCESFUL_UPDATE -eq 1 ]] \
    && notify-send \
        "Dotfiles auto-updater" "Dotfiles automatically updated! Reload shell to apply changes!"\
        -i software-update-available-symbolic \
        -a "Dotfile auto-updater" \
        --transient

[[ $NEEDS_MANUAL_INTERVENTION -eq 1 ]] \
    && notify-send "Dotfiles auto-updater" "Dotfiles can't be updated automatically! Please run 'dotfile pull' manually." \
        -i dialog-warning \
        -u critical \
        -a "Dotfile auto-updater" \
        --transient
