#!/bin/bash

case $1 in
    "screen")
        wayshot --stdout | wl-copy
    ;;

    "area")
        wayshot -s "$(slurp -o -f '%x %y %w %h')" --stdout | wl-copy
    ;;

    *)
        echo "Wrong option! Use: area or screen"
    ;;
esac

notify-send -a Screenshot -i gnome-screenshot-symbolic "Screenshot taken and copied to clipboard."
